from sqlalchemy import Column, String, Text, ForeignKey, Integer, Float, Boolean
from sqlalchemy import Uuid
from sqlalchemy.orm import relationship
import uuid
from app.models.base import Base, TimestampMixin


class PreviousYearQuestion(Base, TimestampMixin):
    __tablename__ = "previous_year_questions"

    file_id = Column(Uuid, ForeignKey("uploaded_files.id"), nullable=True, index=True)
    exam_name = Column(String(300), nullable=False, index=True)
    year = Column(Integer, nullable=False, index=True)
    paper_set = Column(String(50), nullable=True)
    topic = Column(String(300), nullable=True, index=True)
    sub_topic = Column(String(300), nullable=True)
    difficulty = Column(String(50), nullable=True)
    language = Column(String(50), nullable=True)
    question_type = Column(String(100), nullable=True)
    question_text = Column(Text, nullable=False)
    option_a = Column(Text, nullable=True)
    option_b = Column(Text, nullable=True)
    option_c = Column(Text, nullable=True)
    option_d = Column(Text, nullable=True)
    correct_answer = Column(String(10), nullable=True)
    correct_answer_text = Column(Text, nullable=True)
    explanation = Column(Text, nullable=True)
    marks = Column(Integer, nullable=True)
    source_page = Column(Integer, nullable=True)
    keywords = Column(String(500), nullable=True)
    is_verified = Column(Boolean, default=False, nullable=False)
    verification_source = Column(String(500), nullable=True)
    raw_text = Column(Text, nullable=True)

    file = relationship("UploadedFile", back_populates="previous_year_questions")


class QuestionBank(Base, TimestampMixin):
    __tablename__ = "question_bank"

    file_id = Column(Uuid, ForeignKey("uploaded_files.id"), nullable=True, index=True)
    topic_id = Column(Uuid, ForeignKey("topics.id"), nullable=True, index=True)
    sub_topic_id = Column(Uuid, ForeignKey("sub_topics.id"), nullable=True)
    exam_name = Column(String(300), nullable=False, index=True)
    paper_set = Column(String(50), nullable=True)
    topic_name = Column(String(300), nullable=True, index=True)
    sub_topic_name = Column(String(300), nullable=True)
    difficulty = Column(String(50), nullable=False, index=True)
    language = Column(String(50), nullable=False, index=True)
    question_type = Column(String(100), nullable=False)
    question_text = Column(Text, nullable=False)
    option_a = Column(Text, nullable=True)
    option_b = Column(Text, nullable=True)
    option_c = Column(Text, nullable=True)
    option_d = Column(Text, nullable=True)
    correct_answer = Column(String(10), nullable=False)
    correct_answer_text = Column(Text, nullable=True)
    explanation = Column(Text, nullable=True)
    reference_source = Column(String(500), nullable=True)
    source_page_number = Column(Integer, nullable=True)
    weightage = Column(Float, nullable=True)
    keywords = Column(String(500), nullable=True)
    marks = Column(Integer, default=1, nullable=False)
    is_verified = Column(Boolean, default=False, nullable=False)
    verification_status = Column(String(50), default="pending", nullable=False)
    verification_notes = Column(Text, nullable=True)
    grammar_checked = Column(Boolean, default=False, nullable=False)
    fact_checked = Column(Boolean, default=False, nullable=False)
    usage_count = Column(Integer, default=0, nullable=False)
    source = Column(String(100), nullable=True)
    hash = Column(String(128), nullable=True, index=True)

    file = relationship("UploadedFile", back_populates="question_bank_entries")
    topic = relationship("Topic", back_populates="question_bank_entries")
    sub_topic = relationship("SubTopic", back_populates="question_bank_entries")


class GeneratedPaper(Base, TimestampMixin):
    __tablename__ = "generated_papers"

    user_id = Column(Uuid, ForeignKey("users.id"), nullable=False, index=True)
    exam_pattern_id = Column(Uuid, ForeignKey("exam_patterns.id"), nullable=True, index=True)
    exam_name = Column(String(300), nullable=False, index=True)
    paper_set = Column(String(50), nullable=False)
    title = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    language = Column(String(50), nullable=False)
    total_marks = Column(Integer, nullable=False)
    total_questions = Column(Integer, nullable=False)
    duration_minutes = Column(Integer, nullable=True)
    difficulty_profile = Column(String(100), nullable=True)
    instructions_json = Column(Text, nullable=True)
    sections_json = Column(Text, nullable=True)
    question_ids_json = Column(Text, nullable=True)
    pdf_path = Column(String(1000), nullable=True)
    docx_path = Column(String(1000), nullable=True)
    answer_key_path = Column(String(1000), nullable=True)
    is_draft = Column(Boolean, default=False, nullable=False)
    is_published = Column(Boolean, default=False, nullable=False)
    published_at = Column(String(50), nullable=True)
    generation_time_seconds = Column(Float, nullable=True)
    ai_model = Column(String(100), nullable=True)
    prompt_used = Column(Text, nullable=True)
    feedback_score = Column(Float, nullable=True)
    feedback_count = Column(Integer, default=0, nullable=True)

    created_by_user = relationship("User", back_populates="generated_papers")
    exam_pattern = relationship("ExamPattern", back_populates="generated_papers")
    generated_questions = relationship("GeneratedQuestion", back_populates="paper", cascade="all, delete-orphan")
    answer_keys = relationship("AnswerKey", back_populates="paper", cascade="all, delete-orphan")


class GeneratedQuestion(Base, TimestampMixin):
    __tablename__ = "generated_questions"

    paper_id = Column(Uuid, ForeignKey("generated_papers.id"), nullable=False, index=True)
    question_bank_id = Column(Uuid, ForeignKey("question_bank.id"), nullable=True)
    topic_id = Column(Uuid, ForeignKey("topics.id"), nullable=True)
    sub_topic_id = Column(Uuid, ForeignKey("sub_topics.id"), nullable=True)
    exam_name = Column(String(300), nullable=False)
    paper_set = Column(String(50), nullable=False)
    question_number = Column(Integer, nullable=False)
    topic_name = Column(String(300), nullable=True, index=True)
    sub_topic_name = Column(String(300), nullable=True)
    difficulty = Column(String(50), nullable=False, index=True)
    language = Column(String(50), nullable=False, index=True)
    question_type = Column(String(100), nullable=False)
    question_text = Column(Text, nullable=False)
    option_a = Column(Text, nullable=True)
    option_b = Column(Text, nullable=True)
    option_c = Column(Text, nullable=True)
    option_d = Column(Text, nullable=True)
    correct_answer = Column(String(10), nullable=False)
    correct_answer_text = Column(Text, nullable=True)
    explanation = Column(Text, nullable=True)
    reference_source = Column(String(500), nullable=True)
    source_page_number = Column(Integer, nullable=True)
    weightage = Column(Float, nullable=True)
    keywords = Column(String(500), nullable=True)
    marks = Column(Integer, default=1, nullable=False)
    section = Column(String(200), nullable=True)
    is_verified = Column(Boolean, default=False, nullable=False)
    validation_status = Column(String(50), default="pending", nullable=False)
    validation_notes = Column(Text, nullable=True)
    fact_checked = Column(Boolean, default=False, nullable=False)
    grammar_checked = Column(Boolean, default=False, nullable=False)
    option_balance_checked = Column(Boolean, default=False, nullable=False)
    previous_year_similarity = Column(Float, nullable=True)
    hash = Column(String(128), nullable=True, index=True)

    paper = relationship("GeneratedPaper", back_populates="generated_questions")
    topic = relationship("Topic", back_populates="generated_questions")
    sub_topic = relationship("SubTopic", back_populates="generated_questions")
    answer_key = relationship("AnswerKey", back_populates="question", uselist=False)
    explanations = relationship("Explanation", back_populates="question", cascade="all, delete-orphan")
